import { Sarabun } from "next/font/google";
import "./globals.css";

const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "AcuSky",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <html lang="en" className={sarabun.className}>
      {/* suppressHydrationWarning avoids failing hydration if extensions (or other client-only code) mutate attributes */}
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}